### ISSUE TITLE
Check ORM in node (postgres/mongo)

### ISSUE THREAD

**Issue by orgoldfus** [guyisra/leket2#4]
In order to decide which one we should use.

**Comment by orgoldfus** [comment]
So here are my conclusions:

Our use case is easily mapped to a relational schema and I can't see any good reason to use a NoSQL DB.
Therefore, I think we should go with Postgres or MySql.
Postgres is probably more suitable for our needs than MySql (a bit overkill), so that what I focused on.

There is a good Postgres client for node: https://github.com/brianc/node-postgres,
So we can go simple and just use raw queries. It's not that pretty, but I think it won't be a big deal in our case.
Otherwise, we can use http://docs.sequelizejs.com/en/v3/ as ORM, looks like it's the most common ORM for node.

WDYT?

**Comment by guyisra** [comment]
I miss Rails :(

regarding raw queries.. Here is joins chain that I initially used in the old leket to avoid n+1 queries, but I decided to screw it as I didn't really care about performance
https://github.com/hagail/leket-app/blob/master/app/models/pickup_report.rb#L79

While nosql is not really needed, and PG is easy to handle, it might be easier to save data as json in PG (just because its that easy) per pickup per sub supplier, so it will be easier to handle per "row" in the admin interface.

**Comment by orgoldfus** [comment]
I'm not sure it'll be needed if we'll use an ORM, but it sounds like a good solution if we decide to go "raw".
